# Generated by Django 4.0.4 on 2022-07-12 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_r', models.CharField(max_length=255, verbose_name='rev_name')),
                ('email_r', models.CharField(max_length=255, verbose_name='rev_email')),
                ('number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('message', models.TextField(blank=True, null=True)),
                ('image_r', models.ImageField(upload_to='reviews/')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
