# Generated by Django 4.0.4 on 2022-07-13 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_reviews_image_r_alter_reviews_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_del',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date_del'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='decor',
            field=models.ImageField(blank=True, upload_to='decor/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type_del',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type_del'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
