# Generated by Django 4.0.4 on 2022-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_adress_orderitem_date_del_orderitem_decor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_del',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type_del',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_del',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date_del'),
        ),
        migrations.AddField(
            model_name='order',
            name='decor',
            field=models.ImageField(blank=True, upload_to='decor/'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_del',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type_del'),
        ),
    ]
